Blog App : Views
Piercel2022/blog_app pull request #6
Opened 2022-11-17 01:42 UTC by Piercel2022

This pull request is open for the view branch to display the View after the Model and the  Controller was made.
The design is implemented from the sneak peek wireframes. The data that is displaying here in the view are the database records that was entered before when I implemented the database. So now the view show these records.

2022-11-17 03:20 UTC, FrederickMih requested changes
Hi @Piercel2022, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



![Screenshot from 2022-10-20 09-38-51](https://user-images.githubusercontent.com/63087491/201920311-3d7a6eca-bcc4-4e90-aa60-433230b81add.png)

## Highlights :green_circle: 

- Descriptive README.md file :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- PR has a good title and summary :heavy_check_mark: 
- Correct GitHub flow :+1: 



## Required Changes ♻️
N/A
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 03:20 UTC, FrederickMih commented on app/views/posts/index.html.erb
> +        <h3 class="mb-2 text-sm font-bold"><%= post.title %> #<%= post.id %></h3>
- [ ] Let's make sure we are taken to the post-show page by clicking on each post.

2022-11-17 03:20 UTC, FrederickMih commented on app/views/posts/show.html.erb
> +<<h1>Show post</h1>
- [ ] I didn't reach this page. I could not get here by clicking or manually routing on the browser using the URL. I got the console error below.


![Screenshot from 2022-11-17 04-17-29](https://user-images.githubusercontent.com/63087491/202346425-cac88f6c-268e-4bb5-bb78-28d462a1dc6a.png)

- Let's kindly fix :wrench: the error.

2022-11-18 21:55 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Piercel2022, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 21:56 UTC, merged